name: Go

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-tags: true
          fetch-depth: 0
      - name: Build essential
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - uses: actions/setup-go@v6.4.0
        with:
          cache: true
          go-version: '1.25.7'
          cache-dependency-path: |
           ./gitx/go.sum
           ./goserv/go.sum
           ./cliimage/go.sum
           ./goreviewer/go.sum
      - name: Install all tools needed
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          $HOME/go/bin/task install:tools
      - name: Run gofumpt for all packages
        run: $HOME/go/bin/task fmt
      - name: Run base linters for all packages
        run: $HOME/go/bin/task lint
      - name: Build all binaries
        run: |
          cd ./releasex
          go build .
          cd ..
          ./releasex/releasex build
      - name: Run tests for all packages
        run: $HOME/go/bin/task test
        